apiVersion: apps/v1
kind: Deployment
metadata:
  name: sws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sws
  template:
    metadata:
      labels:
        app: sws
    spec:
      containers:
        - name: sws
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources: {{- toYaml .Values.resources | nindent 12 }} 