apiVersion: v1
kind: Service
metadata:
  name: sws
spec:
  type: {{ .Values.service.type }}
  selector:
    app: sws
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http 