[workspace]
resolver = "2"
members = [
    "selenia_core",
    "selenia_http",
    "selenia_server",
]

[[bin]]
name = "bench"
path = "tools/bench.rs"

[[bin]]
name = "bench_scenarios"
path = "tools/bench_scenarios.rs" 