name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}
      - run: cargo fmt --check
      - run: cargo clippy --deny warnings
      - run: cargo test --all --release
      - run: cargo llvm-cov --fail-under 100
      - run: cargo build --release --target ${{ matrix.target }}
  fuzz:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      - run: cargo fuzz run http_parser -- -max_total_time=3600
  bench:
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Run benches
        run: cargo bench | cat
      - name: Compile bench_scenarios
        run: rustc tools/bench_scenarios.rs -O -o bench_scenarios
      - name: Run bench scenarios (skip if tools absent)
        run: ./bench_scenarios all http://127.0.0.1/ | cat
  sbom:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Generate SBOM
        run: |
          cargo install cargo-bom || true
          cargo bom -f json > dist/sbom.json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: dist/sbom.json 